name: website_frontend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  flutter_html: ^2.2.1
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  http: ^0.13.5
  lint: ^1.10.0
  provider: ^6.0.4
  timeline_tile: ^2.0.0
  scrollable_positioned_list: ^0.3.5
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.6
  go_router: ^6.0.0
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/jsons/
  - assets/redakteure/carmen.png
  - assets/redakteure/damian.png
  - assets/redakteure/dariok.png
  - assets/redakteure/darios.png
  - assets/redakteure/diego.png
  - assets/redakteure/dominicm.png
  - assets/redakteure/fabiank.png
  - assets/redakteure/fabio.png
  - assets/redakteure/janick.png
  - assets/redakteure/jose.png
  - assets/redakteure/justin.png
  - assets/redakteure/lukasStuder.png
  - assets/redakteure/manuelm.png
  - assets/redakteure/martin.png
  - assets/redakteure/michelek.png
  - assets/redakteure/noah.png
  - assets/redakteure/olivers.png
  - assets/redakteure/patrickv.png
  - assets/redakteure/phil.png
  - assets/redakteure/raphikoch.png
  - assets/redakteure/reto.png
  - assets/redakteure/stefan.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Oswald
     fonts:
       - asset: assets/fonts/Oswald-Bold.ttf
   - family: Gosler
     fonts:
       - asset: assets/fonts/FONTH.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
