name: Build & Deploy Firebase
on: 
    push:
        branches:
            - develop
jobs:
    hosting:
      name: Deploy Website
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - uses: actions/checkout@v2

        # Install Flutter command
        - uses: subosito/flutter-action@v1
          with:
            channel: "stable"
            flutter-version: '2.8.1'

        # Build Website
        - name: Build Website
          run: |
            flutter config --enable-web
            flutter pub get
            flutter build web --web-renderer canvaskit --release
          working-directory: ./

        # Deploy Firebase Hosting
        - name: Deploy Firebase Hosting
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting:flaeckegosler
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            PROJECT_PATH: ./
